name: "Web (Preview)"

on:
  push:
    branches: [ dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy-web:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Download resoruces
        run: sh ./scripts/download_gdrive_file.sh https://drive.google.com/file/d/1ZEWyh9_QJ1l2_JzlfpPyth8LyGoavzvk
        shell: bash
      - name: Unzip resources
        run: sh ./scripts/unzip_util.sh ./resources.zip
      - name: Index resources
        run: sh ./scripts/index_resources.sh
        shell: bash
      - name: Install prerequisites
        run: sh ./scripts/init_web_assembly.sh
      - name: Build
        run: sh ./scripts/build_web.sh
      - name: Vercel Deployment
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-token: ${{ secrets.VERCEL_GITHUB_TOKEN }}
          working-directory: "web/out"
          scope: ${{ secrets.VERCEL_ORG_ID }}
          github-comment: true
