name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy-web:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install prerequisites
      run: sh ./web/scripts/init_web_assembly.sh
    - name: Build Web
      run: sh ./web/scripts/build_web.sh
    - name: Vercel Deployment
      uses: xmflsct/action-vercel-deployment@v0.5.3
      with:
        vercelToken: ${{ secrets.VERCEL_TOKEN }}
        vercelOrgId: ${{ secrets.VERCEL_ORG_ID }}
        vercelProjectId: ${{ secrets.VERCEL_PROJECT_ID }}
        githubToken: ${{ secrets.VERCEL_GITHUB_TOKEN }}
        deploySource: "web/out"
        deployProduction: true
        assignDomain: ${{ secrets.VERCEL_DOMAIN }}
