name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Web
      run: sh ./web/scripts/build_web.sh
    - name: Vercel Deployment
      uses: xmflsct/action-vercel-deployment@v0.5.3
      with:
        vercelToken: ${{ secrets.vercel_token }}
        vercelOrgId: ${{ secrets.vercel_team }}
        vercelProjectId: ${{ secrets.vercel_project-id }}
        githubToken: ${{ secrets.vercel_github_token }}
        sourceDirectory: "web/out"
        deployProduction: true
        assignDomain: ${{ secrets.vercel_domain }}
